# Generated by Django 2.1.1 on 2019-02-18 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choise'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Choice',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='choise_text',
            new_name='choice_text',
        ),
    ]
